version: "3.8"

services:
  database:
    image: postgres
    ports:
      - 15432:5432
    restart: always
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin_data/:/var/lib/pgadmin/

volumes:
  postgres_data:
  pgadmin_data:

networks:
  postgres-network:
    driver: bridge
